<a href="https://colab.research.google.com/github/annaelyoliveira/Projetos_com_biblioteca_Pandas/blob/main/Projeto_1_%7C_Manipula%C3%A7%C3%A3o_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

1. Baixando uma base de dados em CSV público

In [ ]:
# 2. Carregando base de dados localmente em um DataFrame
df = pd.read_csv('/content/base_de_dados/br_seeg_emissoes_brasil.csv.gz')

In [ ]:
# 3. Carregando base de dados pela URL em um DataFrame

df = pd.read_csv('https://www.w3schools.com/python/pandas/data.csv') #tentei de todas as formas puxar o link csv do download do site do governo porém não consegui, ent fiz com o link do exemplo na aula

Visualizando dados

In [ ]:
# 4. Exibindo as primeiras 15 linhas do DataFrame
df.head(15)

,ano,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,tipo_emissao,gas,atividade_economica,produto,emissao
0,1970,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,230462.17
1,1971,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,226016.30
2,1972,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,220101.20
3,1973,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,214195.56
4,1974,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,186862.84
5,1975,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,197538.20
6,1976,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,231922.02
7,1977,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,209517.92
8,1978,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,174633.98
9,1979,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,162579.47
10,1980,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,188967.84
11,1981,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,175320.74
12,1982,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,163504.10
13,1983,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,156293.07
14,1984,Agropecuária,Cultivo do Arroz,Diretas,Outros,Vegetal,Arroz,Emissão,CH4 (t),NaN,NaN,161026.25

In [ ]:
# 5. Exibindo as últimas 8 linhas do DataFrame

df.tail(8)

,ano,nivel_1,nivel_2,nivel_3,nivel_4,nivel_5,nivel_6,tipo_emissao,gas,atividade_economica,produto,emissao
454842,2012,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,68.095130
454843,2013,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,72.169764
454844,2014,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,74.749533
454845,2015,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,74.195798
454846,2016,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,69.360711
454847,2017,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,69.919672
454848,2018,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,70.507559
454849,2019,Resíduos,Resíduos Sólidos,Tratamento Biológico de Resíduos Sólidos,Resíduos Sólidos Urbanos,Compostagem,NÃO SE APLICA,Emissão,N2O (t),SANEAMENTO,NaN,71.068872

In [ ]:
# 6 Verificando o tamanho do DataFrame e os tipos de dados e valores nulos

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 454850 entries, 0 to 454849
Data columns (total 12 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ano                  454850 non-null  int64
 1   nivel_1              454850 non-null  object
 2   nivel_2              454850 non-null  object
 3   nivel_3              454850 non-null  object
 4   nivel_4              454850 non-null  object
 5   nivel_5              454850 non-null  object
 6   nivel_6              454850 non-null  object
 7   tipo_emissao         454850 non-null  object
 8   gas                  454850 non-null  object
 9   atividade_economica  453100 non-null  object
 10  produto              268100 non-null  object
 11  emissao              406325 non-null  float64
dtypes: float64(1), int64(1), object(10)
memory usage: 41.6+ MB

In [ ]:
# Obtendo as estatísticas das colunas numéricas

df.describe()

                 ano       emissao
count  454850.000000  4.063250e+05
mean     1994.500000  1.437622e+06
std        14.430886  3.124689e+07
min      1970.000000 -3.107000e+08
25%      1982.000000  0.000000e+00
50%      1994.500000  4.689636e+00
75%      2007.000000  4.525840e+04
max      2019.000000  2.083000e+09

8. Salvando o DataFrame carregado nos formatos Excel e JSON

In [ ]:
#Excel

df.to_excel("saida_excel.xlsx", index = False)

In [ ]:
#JSON

df.to_json("saida_json.json", orient = 'records')

9. Criando um banco de dados SQLite e insirindo o DataFrame como uma tabela SQL

In [ ]:
import sqlite3

conexao = sqlite3.connect('banco.db')

df.to_sql('tabela', conexao, if_exists='replace', index = False)

454850

10. Usando uma consulta SQL para selecionar apenas colunas específicas

In [ ]:
# Todas as colunas

df_sql = pd.read_sql_query("SELECT * FROM tabela", conexao)

print(df_sql.head())

    ano       nivel_1           nivel_2  nivel_3 nivel_4  nivel_5 nivel_6  \
0  1970  Agropecuária  Cultivo do Arroz  Diretas  Outros  Vegetal   Arroz
1  1971  Agropecuária  Cultivo do Arroz  Diretas  Outros  Vegetal   Arroz
2  1972  Agropecuária  Cultivo do Arroz  Diretas  Outros  Vegetal   Arroz
3  1973  Agropecuária  Cultivo do Arroz  Diretas  Outros  Vegetal   Arroz
4  1974  Agropecuária  Cultivo do Arroz  Diretas  Outros  Vegetal   Arroz

  tipo_emissao      gas atividade_economica produto    emissao
0      Emissão  CH4 (t)                None    None  230462.17
1      Emissão  CH4 (t)                None    None  226016.30
2      Emissão  CH4 (t)                None    None  220101.20
3      Emissão  CH4 (t)                None    None  214195.56
4      Emissão  CH4 (t)                None    None  186862.84

In [ ]:
# Coluna ano
df_sql = pd.read_sql_query("SELECT ano FROM tabela", conexao)

print(df_sql.head())

    ano
0  1970
1  1971
2  1972
3  1973
4  1974

In [ ]:
#Colunas tipo_emissao e gas

df_sql = pd.read_sql_query("SELECT tipo_emissao, gas FROM tabela", conexao)

print(df_sql.head())

  tipo_emissao      gas
0      Emissão  CH4 (t)
1      Emissão  CH4 (t)
2      Emissão  CH4 (t)
3      Emissão  CH4 (t)
4      Emissão  CH4 (t)